In [ ]:
import numpy as np

In [ ]:
X = np.array ([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

In [ ]:
X

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

### 전치행렬 (Transposed Matrix)

전치행렬은 행렬의 행과 열이 뒤바뀐 모양. T를 거듭제곱의 모양으로 써 표시함.

In [ ]:
# 전치행렬 만드는 기본 방법
X_transpose = np.transpose(X)
X_transpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [ ]:
# 전치행렬 만드는 가장 쉬운 방법 "T"
X_transpose = X.T
X_transpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

### 단위행렬 (Identity Matrix)

단위행렬은 주대각전의 원소가 모두 1이며 나머지 원소는 모두 0인 행렬.

In [ ]:
# 단위행렬 만들기
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 행렬의 곱
X @ I

array([[ 1., -1.,  2.],
       [ 3.,  2.,  2.],
       [ 4.,  1.,  2.]])

### 역행렬 (Inverse Matrix)

역행렬은 어떤 행렬에 곱하여 단위행렬이 나오게 해주는 것.

모든 행렬이 역행렬을 가지진 않음. 단, 코딩에서 pinv함수는 역행렬이 없어도 역행렬과 최대한 비슷한 효과를 내는 값을 찾아 리턴.

In [ ]:
X_inverse = np.linalg.pinv(X)
X_inverse

array([[-0.2, -0.4,  0.6],
       [-0.2,  0.6, -0.4],
       [ 0.5,  0.5, -0.5]])

In [ ]:
# 행렬의 곱
X @ X_inverse

array([[ 1.00000000e+00,  5.55111512e-16, -8.88178420e-16],
       [ 0.00000000e+00,  1.00000000e+00, -8.88178420e-16],
       [ 0.00000000e+00,  3.33066907e-16,  1.00000000e+00]])